services:
  reader:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - cache-volume:/var/lib/cache
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "-w", "4", "app:get_production_flask_app(\"/var/lib/cache\")"]
  writer:
    build:
      context: .
    volumes:
      - cache-volume:/var/lib/cache
    command: ["python", "app.py", "writer", "--cache-location", "/var/lib/cache"]

volumes:
  cache-volume:
